// GENERATED by scripts/generate-currency-catalog.mjs — DO NOT EDIT BY HAND
// Re-run the script to regenerate.
//
// Catálogo completo de monedas ISO-4217 activas (Intl.supportedValuesOf),
// con nombre en español (Intl.DisplayNames), locale de formateo, símbolo y
// dígitos decimales (Intl.NumberFormat). Orden: prioritarias (contexto LATAM
// dental) primero, luego el resto alfabético por nombre en español.

/** Entrada del catálogo de monedas. */
export interface CurrencyCatalogEntry {
  /** Código ISO-4217 (ej. "USD"). */
  code: string;
  /** Nombre en español, con mayúscula inicial (ej. "Dólar estadounidense"). */
  name: string;
  /** Locale usado para formatear esta moneda con Intl.NumberFormat. */
  locale: string;
  /** Símbolo de la moneda (o el código si Intl no provee símbolo). */
  symbol: string;
  /** Dígitos decimales estándar de la moneda (maximumFractionDigits). */
  decimalDigits: number;
}

/** Catálogo completo de monedas ISO-4217 activas (`162` entradas). */
export const CURRENCY_CATALOG: readonly CurrencyCatalogEntry[] = [
  { code: "USD", name: "Dólar estadounidense", locale: "es-US", symbol: "$", decimalDigits: 2 },
  { code: "EUR", name: "Euro", locale: "es-ES", symbol: "€", decimalDigits: 2 },
  { code: "BOB", name: "Boliviano", locale: "es-BO", symbol: "Bs", decimalDigits: 2 },
  { code: "COP", name: "Peso colombiano", locale: "es-CO", symbol: "$", decimalDigits: 0 },
  { code: "MXN", name: "Peso mexicano", locale: "es-MX", symbol: "$", decimalDigits: 2 },
  { code: "ARS", name: "Peso argentino", locale: "es-AR", symbol: "$", decimalDigits: 2 },
  { code: "PEN", name: "Sol peruano", locale: "es-PE", symbol: "S/", decimalDigits: 2 },
  { code: "CLP", name: "Peso chileno", locale: "es-CL", symbol: "$", decimalDigits: 0 },
  { code: "BRL", name: "Real brasileño", locale: "pt-BR", symbol: "R$", decimalDigits: 2 },
  { code: "UYU", name: "Peso uruguayo", locale: "es-UY", symbol: "$", decimalDigits: 2 },
  { code: "PYG", name: "Guaraní paraguayo", locale: "es-PY", symbol: "Gs.", decimalDigits: 0 },
  { code: "VES", name: "Bolívar venezolano", locale: "es-VE", symbol: "Bs.S", decimalDigits: 2 },
  { code: "GTQ", name: "Quetzal guatemalteco", locale: "es-GT", symbol: "Q", decimalDigits: 2 },
  { code: "CRC", name: "Colón costarricense", locale: "es-CR", symbol: "₡", decimalDigits: 2 },
  { code: "DOP", name: "Peso dominicano", locale: "es-DO", symbol: "RD$", decimalDigits: 2 },
  { code: "HNL", name: "Lempira hondureño", locale: "es-HN", symbol: "L", decimalDigits: 2 },
  { code: "NIO", name: "Córdoba", locale: "es-NI", symbol: "C$", decimalDigits: 2 },
  { code: "PAB", name: "Balboa panameño", locale: "es-PA", symbol: "B/.", decimalDigits: 2 },
  { code: "GBP", name: "Libra esterlina", locale: "en-GB", symbol: "£", decimalDigits: 2 },
  { code: "AFN", name: "Afgani afgano", locale: "es-419", symbol: "AFN", decimalDigits: 0 },
  { code: "MGA", name: "Ariari malgache", locale: "es-419", symbol: "MGA", decimalDigits: 0 },
  { code: "THB", name: "Bat tailandés", locale: "es-419", symbol: "THB", decimalDigits: 2 },
  { code: "ETB", name: "Bir etíope", locale: "es-419", symbol: "ETB", decimalDigits: 2 },
  { code: "GHS", name: "Cedi ghanés", locale: "es-419", symbol: "GHS", decimalDigits: 2 },
  { code: "KES", name: "Chelín keniano", locale: "es-419", symbol: "KES", decimalDigits: 2 },
  { code: "SOS", name: "Chelín somalí", locale: "es-419", symbol: "SOS", decimalDigits: 0 },
  { code: "TZS", name: "Chelín tanzano", locale: "es-419", symbol: "TZS", decimalDigits: 2 },
  { code: "UGX", name: "Chelín ugandés", locale: "es-419", symbol: "UGX", decimalDigits: 0 },
  { code: "SVC", name: "Colón salvadoreño", locale: "es-419", symbol: "SVC", decimalDigits: 2 },
  { code: "CZK", name: "Corona checa", locale: "es-419", symbol: "CZK", decimalDigits: 2 },
  { code: "DKK", name: "Corona danesa", locale: "es-419", symbol: "DKK", decimalDigits: 2 },
  { code: "ISK", name: "Corona islandesa", locale: "es-419", symbol: "ISK", decimalDigits: 0 },
  { code: "NOK", name: "Corona noruega", locale: "es-419", symbol: "NOK", decimalDigits: 2 },
  { code: "SEK", name: "Corona sueca", locale: "es-419", symbol: "SEK", decimalDigits: 2 },
  { code: "GMD", name: "Dalasi gambiano", locale: "es-419", symbol: "GMD", decimalDigits: 2 },
  { code: "XDR", name: "Derechos especiales de giro", locale: "es-419", symbol: "XDR", decimalDigits: 2 },
  { code: "DZD", name: "Dinar argelino", locale: "es-419", symbol: "DZD", decimalDigits: 2 },
  { code: "BHD", name: "Dinar bareiní", locale: "es-419", symbol: "BHD", decimalDigits: 3 },
  { code: "IQD", name: "Dinar iraquí", locale: "es-419", symbol: "IQD", decimalDigits: 0 },
  { code: "JOD", name: "Dinar jordano", locale: "es-419", symbol: "JOD", decimalDigits: 3 },
  { code: "KWD", name: "Dinar kuwaití", locale: "es-419", symbol: "KWD", decimalDigits: 3 },
  { code: "LYD", name: "Dinar libio", locale: "es-419", symbol: "LYD", decimalDigits: 3 },
  { code: "MKD", name: "Dinar macedonio", locale: "es-419", symbol: "MKD", decimalDigits: 2 },
  { code: "RSD", name: "Dinar serbio", locale: "es-419", symbol: "RSD", decimalDigits: 2 },
  { code: "TND", name: "Dinar tunecino", locale: "es-419", symbol: "TND", decimalDigits: 3 },
  { code: "AED", name: "Dírham emiratí", locale: "es-419", symbol: "AED", decimalDigits: 2 },
  { code: "MAD", name: "Dírham marroquí", locale: "es-419", symbol: "MAD", decimalDigits: 2 },
  { code: "STN", name: "Dobra santotomense", locale: "es-419", symbol: "STN", decimalDigits: 2 },
  { code: "AUD", name: "Dólar australiano", locale: "es-419", symbol: "AUD", decimalDigits: 2 },
  { code: "BSD", name: "Dólar bahameño", locale: "es-419", symbol: "BSD", decimalDigits: 2 },
  { code: "BBD", name: "Dólar barbadense", locale: "es-419", symbol: "BBD", decimalDigits: 2 },
  { code: "BZD", name: "Dólar beliceño", locale: "es-419", symbol: "BZD", decimalDigits: 2 },
  { code: "BMD", name: "Dólar bermudeño", locale: "es-419", symbol: "BMD", decimalDigits: 2 },
  { code: "BND", name: "Dólar bruneano", locale: "es-419", symbol: "BND", decimalDigits: 2 },
  { code: "CAD", name: "Dólar canadiense", locale: "es-419", symbol: "CAD", decimalDigits: 2 },
  { code: "KYD", name: "Dólar de las Islas Caimán", locale: "es-419", symbol: "KYD", decimalDigits: 2 },
  { code: "TTD", name: "Dólar de Trinidad y Tobago", locale: "es-419", symbol: "TTD", decimalDigits: 2 },
  { code: "XCD", name: "Dólar del Caribe Oriental", locale: "es-419", symbol: "XCD", decimalDigits: 2 },
  { code: "FJD", name: "Dólar fiyiano", locale: "es-419", symbol: "FJD", decimalDigits: 2 },
  { code: "GYD", name: "Dólar guyanés", locale: "es-419", symbol: "GYD", decimalDigits: 2 },
  { code: "HKD", name: "Dólar hongkonés", locale: "es-419", symbol: "HKD", decimalDigits: 2 },
  { code: "JMD", name: "Dólar jamaicano", locale: "es-419", symbol: "JMD", decimalDigits: 2 },
  { code: "LRD", name: "Dólar liberiano", locale: "es-419", symbol: "LRD", decimalDigits: 2 },
  { code: "NAD", name: "Dólar namibio", locale: "es-419", symbol: "NAD", decimalDigits: 2 },
  { code: "NZD", name: "Dólar neozelandés", locale: "es-419", symbol: "NZD", decimalDigits: 2 },
  { code: "SBD", name: "Dólar salomonense", locale: "es-419", symbol: "SBD", decimalDigits: 2 },
  { code: "SGD", name: "Dólar singapurense", locale: "es-419", symbol: "SGD", decimalDigits: 2 },
  { code: "SRD", name: "Dólar surinamés", locale: "es-419", symbol: "SRD", decimalDigits: 2 },
  { code: "ZWL", name: "Dólar zimbabuense", locale: "es-419", symbol: "ZWL", decimalDigits: 2 },
  { code: "VND", name: "Dong vietnamita", locale: "es-419", symbol: "VND", decimalDigits: 0 },
  { code: "AMD", name: "Dram armenio", locale: "es-419", symbol: "AMD", decimalDigits: 2 },
  { code: "CVE", name: "Escudo de Cabo Verde", locale: "es-419", symbol: "CVE", decimalDigits: 2 },
  { code: "PLN", name: "Esloti polaco", locale: "es-419", symbol: "PLN", decimalDigits: 2 },
  { code: "ANG", name: "Florín antillano", locale: "es-419", symbol: "ANG", decimalDigits: 2 },
  { code: "AWG", name: "Florín arubeño", locale: "es-419", symbol: "AWG", decimalDigits: 2 },
  { code: "XCG", name: "Florín caribeño", locale: "es-419", symbol: "Cg.", decimalDigits: 2 },
  { code: "HUF", name: "Forinto húngaro", locale: "es-419", symbol: "HUF", decimalDigits: 0 },
  { code: "BIF", name: "Franco burundés", locale: "es-419", symbol: "BIF", decimalDigits: 0 },
  { code: "XAF", name: "Franco CFA de África Central", locale: "es-419", symbol: "XAF", decimalDigits: 0 },
  { code: "XOF", name: "Franco CFA de África Occidental", locale: "es-419", symbol: "XOF", decimalDigits: 0 },
  { code: "XPF", name: "Franco CFP", locale: "es-419", symbol: "CFPF", decimalDigits: 0 },
  { code: "KMF", name: "Franco comorense", locale: "es-419", symbol: "KMF", decimalDigits: 0 },
  { code: "CDF", name: "Franco congoleño", locale: "es-419", symbol: "CDF", decimalDigits: 2 },
  { code: "GNF", name: "Franco guineano", locale: "es-419", symbol: "GNF", decimalDigits: 0 },
  { code: "RWF", name: "Franco ruandés", locale: "es-419", symbol: "RWF", decimalDigits: 0 },
  { code: "CHF", name: "Franco suizo", locale: "es-419", symbol: "CHF", decimalDigits: 2 },
  { code: "DJF", name: "Franco yibutiano", locale: "es-419", symbol: "DJF", decimalDigits: 0 },
  { code: "UAH", name: "Grivna ucraniana", locale: "es-419", symbol: "UAH", decimalDigits: 2 },
  { code: "BTN", name: "Gultrum butanés", locale: "es-419", symbol: "BTN", decimalDigits: 2 },
  { code: "HTG", name: "Gurde haitiano", locale: "es-419", symbol: "HTG", decimalDigits: 2 },
  { code: "MMK", name: "Kiat de Myanmar", locale: "es-419", symbol: "MMK", decimalDigits: 0 },
  { code: "PGK", name: "Kina papú", locale: "es-419", symbol: "PGK", decimalDigits: 2 },
  { code: "LAK", name: "Kip laosiano", locale: "es-419", symbol: "LAK", decimalDigits: 0 },
  { code: "MWK", name: "Kuacha malauí", locale: "es-419", symbol: "MWK", decimalDigits: 2 },
  { code: "ZMW", name: "Kuacha zambiano", locale: "es-419", symbol: "ZMW", decimalDigits: 2 },
  { code: "AOA", name: "Kuanza angoleño", locale: "es-419", symbol: "AOA", decimalDigits: 2 },
  { code: "HRK", name: "Kuna croata", locale: "es-419", symbol: "HRK", decimalDigits: 2 },
  { code: "GEL", name: "Lari georgiano", locale: "es-419", symbol: "GEL", decimalDigits: 2 },
  { code: "ALL", name: "Lek albanés", locale: "es-419", symbol: "ALL", decimalDigits: 0 },
  { code: "SLE", name: "Leona sierraleonesa", locale: "es-419", symbol: "SLE", decimalDigits: 2 },
  { code: "SLL", name: "Leona sierraleonesa (antigua)", locale: "es-419", symbol: "SLL", decimalDigits: 0 },
  { code: "MDL", name: "Leu moldavo", locale: "es-419", symbol: "MDL", decimalDigits: 2 },
  { code: "RON", name: "Leu rumano", locale: "es-419", symbol: "RON", decimalDigits: 2 },
  { code: "BGN", name: "Leva búlgara", locale: "es-419", symbol: "BGN", decimalDigits: 2 },
  { code: "SHP", name: "Libra de Santa Elena", locale: "es-419", symbol: "SHP", decimalDigits: 2 },
  { code: "EGP", name: "Libra egipcia", locale: "es-419", symbol: "EGP", decimalDigits: 2 },
  { code: "GIP", name: "Libra gibraltareña", locale: "es-419", symbol: "GIP", decimalDigits: 2 },
  { code: "LBP", name: "Libra libanesa", locale: "es-419", symbol: "LBP", decimalDigits: 0 },
  { code: "FKP", name: "Libra malvinense", locale: "es-419", symbol: "FKP", decimalDigits: 2 },
  { code: "SYP", name: "Libra siria", locale: "es-419", symbol: "SYP", decimalDigits: 0 },
  { code: "SDG", name: "Libra sudanesa", locale: "es-419", symbol: "SDG", decimalDigits: 2 },
  { code: "SSP", name: "Libra sursudanesa", locale: "es-419", symbol: "SSP", decimalDigits: 2 },
  { code: "SZL", name: "Lilangeni esuatiní", locale: "es-419", symbol: "SZL", decimalDigits: 2 },
  { code: "TRY", name: "Lira turca", locale: "es-419", symbol: "TRY", decimalDigits: 2 },
  { code: "LSL", name: "Loti lesotense", locale: "es-419", symbol: "LSL", decimalDigits: 2 },
  { code: "AZN", name: "Manat azerbaiyano", locale: "es-419", symbol: "AZN", decimalDigits: 2 },
  { code: "TMT", name: "Manat turcomano", locale: "es-419", symbol: "TMT", decimalDigits: 2 },
  { code: "BAM", name: "Marco convertible bosnio", locale: "es-419", symbol: "BAM", decimalDigits: 2 },
  { code: "MZN", name: "Metical mozambiqueño", locale: "es-419", symbol: "MZN", decimalDigits: 2 },
  { code: "NGN", name: "Naira nigeriano", locale: "es-419", symbol: "NGN", decimalDigits: 2 },
  { code: "ERN", name: "Nakfa eritreo", locale: "es-419", symbol: "ERN", decimalDigits: 2 },
  { code: "TWD", name: "Nuevo dólar taiwanés", locale: "es-419", symbol: "TWD", decimalDigits: 2 },
  { code: "ILS", name: "Nuevo séquel israelí", locale: "es-419", symbol: "ILS", decimalDigits: 2 },
  { code: "ZWG", name: "Oro zimbabuense", locale: "es-419", symbol: "ZWG", decimalDigits: 2 },
  { code: "TOP", name: "Paanga tongano", locale: "es-419", symbol: "TOP", decimalDigits: 2 },
  { code: "MOP", name: "Pataca macaense", locale: "es-419", symbol: "MOP", decimalDigits: 2 },
  { code: "CUP", name: "Peso cubano", locale: "es-419", symbol: "CUP", decimalDigits: 2 },
  { code: "CUC", name: "Peso cubano convertible", locale: "es-419", symbol: "CUC", decimalDigits: 2 },
  { code: "PHP", name: "Peso filipino", locale: "es-419", symbol: "PHP", decimalDigits: 2 },
  { code: "BWP", name: "Pula botsuano", locale: "es-419", symbol: "BWP", decimalDigits: 2 },
  { code: "ZAR", name: "Rand sudafricano", locale: "es-419", symbol: "ZAR", decimalDigits: 2 },
  { code: "QAR", name: "Rial catarí", locale: "es-419", symbol: "QAR", decimalDigits: 2 },
  { code: "IRR", name: "Rial iraní", locale: "es-419", symbol: "IRR", decimalDigits: 0 },
  { code: "OMR", name: "Rial omaní", locale: "es-419", symbol: "OMR", decimalDigits: 3 },
  { code: "SAR", name: "Rial saudí", locale: "es-419", symbol: "SAR", decimalDigits: 2 },
  { code: "YER", name: "Rial yemení", locale: "es-419", symbol: "YER", decimalDigits: 0 },
  { code: "KHR", name: "Riel camboyano", locale: "es-419", symbol: "KHR", decimalDigits: 2 },
  { code: "MYR", name: "Ringit malasio", locale: "es-419", symbol: "MYR", decimalDigits: 2 },
  { code: "BYN", name: "Rublo bielorruso", locale: "es-419", symbol: "BYN", decimalDigits: 2 },
  { code: "RUB", name: "Rublo ruso", locale: "es-419", symbol: "RUB", decimalDigits: 2 },
  { code: "MVR", name: "Rufiya maldiva", locale: "es-419", symbol: "MVR", decimalDigits: 2 },
  { code: "LKR", name: "Rupia esrilanquesa", locale: "es-419", symbol: "LKR", decimalDigits: 2 },
  { code: "INR", name: "Rupia india", locale: "es-419", symbol: "INR", decimalDigits: 2 },
  { code: "IDR", name: "Rupia indonesia", locale: "es-419", symbol: "IDR", decimalDigits: 0 },
  { code: "MUR", name: "Rupia mauriciana", locale: "es-419", symbol: "MUR", decimalDigits: 2 },
  { code: "NPR", name: "Rupia nepalí", locale: "es-419", symbol: "NPR", decimalDigits: 2 },
  { code: "PKR", name: "Rupia pakistaní", locale: "es-419", symbol: "PKR", decimalDigits: 0 },
  { code: "SCR", name: "Rupia seychellense", locale: "es-419", symbol: "SCR", decimalDigits: 2 },
  { code: "KGS", name: "Som kirguís", locale: "es-419", symbol: "KGS", decimalDigits: 2 },
  { code: "TJS", name: "Somoni tayiko", locale: "es-419", symbol: "TJS", decimalDigits: 2 },
  { code: "XSU", name: "Sucre (ALBA)", locale: "es-419", symbol: "XSU", decimalDigits: 2 },
  { code: "UZS", name: "Sum uzbeko", locale: "es-419", symbol: "UZS", decimalDigits: 2 },
  { code: "BDT", name: "Taka bangladesí", locale: "es-419", symbol: "BDT", decimalDigits: 2 },
  { code: "WST", name: "Tala samoano", locale: "es-419", symbol: "WST", decimalDigits: 2 },
  { code: "KZT", name: "Tengue kazajo", locale: "es-419", symbol: "KZT", decimalDigits: 2 },
  { code: "MNT", name: "Tugrik mongol", locale: "es-419", symbol: "MNT", decimalDigits: 2 },
  { code: "MRU", name: "Uguiya mauritano", locale: "es-419", symbol: "MRU", decimalDigits: 2 },
  { code: "VUV", name: "Vatu vanuatense", locale: "es-419", symbol: "VUV", decimalDigits: 0 },
  { code: "KPW", name: "Won norcoreano", locale: "es-419", symbol: "KPW", decimalDigits: 0 },
  { code: "KRW", name: "Won surcoreano", locale: "es-419", symbol: "KRW", decimalDigits: 0 },
  { code: "JPY", name: "Yen japonés", locale: "es-419", symbol: "JPY", decimalDigits: 0 },
  { code: "CNY", name: "Yuan chino", locale: "es-419", symbol: "CNY", decimalDigits: 2 },
];

/** Opciones para el control `Select` de moneda. Label: "CODE - Nombre". */
export const CURRENCY_OPTIONS: readonly { value: string; label: string }[] =
  CURRENCY_CATALOG.map((entry) => ({
    value: entry.code,
    label: `${entry.code} - ${entry.name}`,
  }));

/** Mapa código→locale, usado para formateo con Intl.NumberFormat. */
export const CURRENCY_LOCALE_BY_CODE: Readonly<Record<string, string>> =
  Object.fromEntries(CURRENCY_CATALOG.map((entry) => [entry.code, entry.locale]));

/** Set de códigos ISO-4217 soportados por el catálogo. */
export const CURRENCY_CODES: ReadonlySet<string> = new Set(
  CURRENCY_CATALOG.map((entry) => entry.code),
);

/** Moneda por defecto de la clínica. */
export const DEFAULT_CURRENCY = "USD";

/** Indica si `code` es una moneda ISO-4217 soportada por el catálogo. */
export function isSupportedCurrency(code: string): boolean {
  return CURRENCY_CODES.has(code?.trim().toUpperCase());
}
